(()=>{
 const u=new URL(location.href), chosen=u.searchParams.get('lang');
 if(chosen==='en'||chosen==='ko'){localStorage.setItem('ovov_lang',chosen);u.searchParams.delete('lang');const dest=u.pathname+(chosen==='ko'?'ko.html':'index.html');location.replace(dest+u.search+u.hash);return}
 const pref=localStorage.getItem('ovov_lang');
 if(pref==='ko'&&!location.pathname.endsWith('ko.html')){location.replace(location.pathname.replace(/index\.html$/,'')+'ko.html'+location.search+location.hash);return}
 if(pref==='en'&&location.pathname.endsWith('ko.html')){location.replace(location.pathname.replace(/ko\.html$/,'')+location.search+location.hash);return}
 document.querySelectorAll('a[href^="/"]').forEach(a=>{if(a.pathname.includes('/assets/'))return;a.addEventListener('click',ev=>{const p=localStorage.getItem('ovov_lang');if(p==='ko'&&!a.search&&!a.href.includes('?lang=')){ev.preventDefault();location.href=a.getAttribute('href')+'ko.html'}})});
 const menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>{const nav=document.querySelector('#site-nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
 document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{const node=document.getElementById(btn.dataset.copy);try{await navigator.clipboard.writeText(node.innerText.trim());const old=btn.textContent;btn.textContent='Copied!';setTimeout(()=>btn.textContent=old,1800)}catch{btn.textContent='Copy failed'}}));
 const box=document.querySelector('.lightbox');if(box){const image=box.querySelector('img'),download=box.querySelector('a'),close=box.querySelector('.lightbox-close');let previous;const shut=()=>{box.hidden=true;document.body.style.overflow='';previous?.focus()};document.querySelectorAll('.zoom').forEach(button=>button.addEventListener('click',()=>{previous=button;image.src=button.dataset.src;image.alt=button.dataset.alt;download.href=button.dataset.src;box.hidden=false;document.body.style.overflow='hidden';close.focus()}));close.addEventListener('click',shut);box.addEventListener('click',e=>{if(e.target===box)shut()});document.addEventListener('keydown',e=>{if(box.hidden)return;if(e.key==='Escape')shut();if(e.key==='Tab'){const els=[close,download];if(e.shiftKey&&document.activeElement===close){e.preventDefault();download.focus()}else if(!e.shiftKey&&document.activeElement===download){e.preventDefault();close.focus()}}})}
})();
